import type {NextPage} from 'next';
import Link from 'next/link';
import Head from 'next/head';
import Header from './../components/Header';
import Hero from './../components/Hero';
import About from './../components/About';
import Experience from './../components/Experience';
import Skills from './../components/Skills';
import Projects from './../components/Projects';
import ContactMe from './../components/ContactMe';
import {ArrowUpCircleIcon} from '@heroicons/react/24/solid';

const Home: NextPage = () => {
  return (
    <>
      <div className='bg-[rgb(55,55,55)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-500/20 scrollbar-thumb-[#F7AB0A]/80'>
        <Head>
          <title>Jen Tchai | Frontend Developer | Portfolio Site</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 

        <Header />

        <section id='hero' className='snap-start'>
          <Hero />
        </section>

        <section id='about' className='snap-center'>
          <About />
        </section>

        <section id='experience' className='snap-center'>
          <Experience />
        </section>

        <section id='skills' className='snap-start'>
          <Skills />
        </section>

        <section id='projects' className='snap-start'>
          <Projects />
        </section>

        <section id='contact' className='snap-start'>
          <ContactMe />
        </section>

        <Link href='#hero'>
          <footer className='sticky bottom-5 w-full cursor-pointer'>
            <div className='flex items-center justify-center'>
              <button className='h-10 w-10 rounded-full filter hover:transform-[50%] cursor-pointer'>
                <ArrowUpCircleIcon className='text-[#FBC101] h-8 w-8' />
              </button>
            </div>
          </footer>
        </Link>
      </div>
    </>
  )
};

export default Home;
