import type {NextPage} from 'next';
import Head from 'next/head';
import Header from './../components/Header';
import Hero from './../components/Hero';

const Home: NextPage = () => {
  return (
    <>
      <div className='bg-[rgb(55,55,55)] text-white h-screen snap-y snap'>
        <Head>
          <title>Jen Tchai | Portfolio Site</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        {/* <h1 className='p-10 text-red-500'>testing</h1> */}
        <Header />

        {/* Hero */}
        <section id='hero'>
          <Hero />
        </section>

        {/* About me */}

        {/* Experiences */}

        {/* Skills */}

        {/* Projects */}

        {/* Contact me */}
      </div>
    </>
  )
};

export default Home;
